name: update-flake-lock-dev
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 10 1,14 * *"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Install Nix
        uses: cachix/install-nix-action@v22
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          path-to-flake-dir: ./dev
          pr-title: "Update dev flake.lock"
          pr-labels: |
            dependencies
            automated
